# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85a0cd2aa7ebae3ecebb70261b66b29a8c857d1cb46e2ce519a36c6df8d829db04d816f7497a77dfa8d24a58fb379673d7bc1b6cadc1806f769a425b45cedbde

test:
  secret_key_base: 46e9a97b87bcdc03d52cbb913fadcf1afb2a94f68201f63b1cda4ac64d4e27b5e67c8409d9655cd0e2840d3226cf9647396790b7851b4662d719d81ffb3b1eb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
